In [3]:
import numpy as np

In [ ]:
1.Create an array and find sum of it.

In [9]:
data=np.random.randint(1,10,(3,3))
print(data)
data.sum()

[[5 7 6]
 [4 8 3]
 [2 5 5]]


45

In [ ]:
2.Find sin of given array.

In [17]:
data=np.random.randint(1,10,(3,3))
np.sin(data)

array([[ 0.6569866 ,  0.84147098,  0.41211849],
       [-0.95892427,  0.6569866 ,  0.90929743],
       [ 0.90929743,  0.14112001, -0.2794155 ]])

In [ ]:
3.Find mean of matrix along row and column.

In [15]:
data=np.random.randint(1,10,(3,3))
data.mean(axis=1)

array([8.        , 3.33333333, 4.66666667])

In [16]:
data.mean(axis=0)

array([5., 6., 5.])

In [ ]:
4. Find standard deviation of given array.

In [23]:
arr=np.random.randint(1,10,(1,10))
st=np.std(arr)
st

2.039607805437114

In [ ]:
5. Create a 3*3 matrix and print it's transpose matrix

In [43]:
matrix=np.random.randint(1,100,(3,3))
print(matrix)
print(matrix.transpose())

[[92 33 91]
 [23 30 36]
 [13  1 76]]
[[92 23 13]
 [33 30  1]
 [91 36 76]]


In [ ]:
6. Create an array of 3*3 and find index of max along both axis.

In [54]:
data=np.random.randint(1,100,(3,3))
print(data)
print(np.where(data == data.max()))

[[37 21 66]
 [52 22 39]
 [58 58 44]]
(array([0], dtype=int64), array([2], dtype=int64))


In [ ]:
7. find sum of two matrix.

In [59]:
matrix1=np.random.randint(1,120,(3,3))
matrix2=np.random.randint(1,120,(3,3))
sum1=sum(matrix1)
sum2=sum(matrix2)
print(sum1+sum2)

[356 337 419]


In [ ]:
8. Find indexes of max element along axis=0 and axis=1.

In [64]:
arr=np.random.randint(1,120,(3,3))
print(arr)
print(np.argmax(arr,axis=0))#col
print(np.argmax(arr,axis=1))#row

[[106  81  46]
 [ 61  97  17]
 [ 95  41  83]]
[0 1 2]
[0 1 0]


In [ ]:
9. Write a program to add two arrays of different shape.

In [ ]:
10. Try to solve a array and print a array with indices which would sort the given array.

In [68]:
arr=np.array([3,1,8,2])
print(np.argsort(arr))

[1 3 0 2]


In [ ]:
11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.

In [77]:
arr=np.random.randint(1,111,(3,3))
print(arr)
print("Column Indices",np.argsort(arr,axis=0))#column
print("Row Indices",np.argsort(arr,axis=1))#row

[[108  45  70]
 [  9  36   6]
 [ 59 110   4]]
Column Indices [[1 1 2]
 [2 0 1]
 [0 2 0]]
Row Indices [[1 2 0]
 [2 0 1]
 [2 0 1]]


In [ ]:
12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.

In [79]:
matrix=np.random.randint(1,99,(3,3))
print(matrix)
maxtrix1=matrix.transpose()
print(matrix1)
print(matrix.dot(matrix1))

[[89 63 74]
 [86 61 85]
 [67 62 13]]
[[12530 14190  9961]
 [12688 14413 10979]
 [ 9242 10049  3738]]


In [ ]:
15. Find cube of a mtrix.

In [82]:
matrix=np.random.randint(1,99,(3,3))
print(matrix)
print(np.cbrt(matrix))

[[ 3 98 65]
 [59 36 28]
 [30 44 73]]
[[1.44224957 4.61043629 4.02072576]
 [3.89299642 3.30192725 3.03658897]
 [3.10723251 3.53034834 4.1793392 ]]
