In [2]:
import numpy as np

In [ ]:
1.Create an array and find sum of it.

In [9]:
data=np.random.randint(1,10,(3,3))
print(data)
data.sum()

[[5 7 6]
 [4 8 3]
 [2 5 5]]


45

In [ ]:
2.Find sin of given array.

In [17]:
data=np.random.randint(1,10,(3,3))
np.sin(data)

array([[ 0.6569866 ,  0.84147098,  0.41211849],
       [-0.95892427,  0.6569866 ,  0.90929743],
       [ 0.90929743,  0.14112001, -0.2794155 ]])

In [ ]:
3.Find mean of matrix along row and column.

In [15]:
data=np.random.randint(1,10,(3,3))
data.mean(axis=1)

array([8.        , 3.33333333, 4.66666667])

In [16]:
data.mean(axis=0)

array([5., 6., 5.])

In [ ]:
4. Find standard deviation of given array.

In [23]:
arr=np.random.randint(1,10,(1,10))
st=np.std(arr)
st

2.039607805437114

In [ ]:
5. Create a 3*3 matrix and print it's transpose matrix

In [43]:
matrix=np.random.randint(1,100,(3,3))
print(matrix)
print(matrix.transpose())#T

[[92 33 91]
 [23 30 36]
 [13  1 76]]
[[92 23 13]
 [33 30  1]
 [91 36 76]]


In [ ]:
6. Create an array of 3*3 and find index of max along both axis.

In [3]:
data=np.random.randint(1,100,(3,3))
print(data)
print(data.argmax(axis=0))
print(data.argmax(axis=1))

[[84 61 89]
 [83 56 51]
 [ 1 43 45]]
[0 0 0]
[2 0 2]


In [ ]:
7. find sum of two matrix.

In [59]:
matrix1=np.random.randint(1,120,(3,3))
matrix2=np.random.randint(1,120,(3,3))
sum1=sum(matrix1)
sum2=sum(matrix2)
print(sum1+sum2)

[356 337 419]


In [ ]:
8. Find indexes of max element along axis=0 and axis=1.

In [4]:
arr=np.random.randint(1,120,(3,3))
print(arr)
print(arr.max(axis=0))#col
print(arr.max(axis=1))#row

[[101   3  66]
 [ 93  27  13]
 [ 35  23   9]]
[101  27  66]
[101  93  35]


In [ ]:
9. Write a program to add two arrays of different shape.

In [5]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis]+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
10. Try to solve a array and print a array with indices which would sort the given array.

In [68]:
arr=np.array([3,1,8,2])
print(np.argsort(arr))

[1 3 0 2]


In [ ]:
11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.

In [77]:
arr=np.random.randint(1,111,(3,3))
print(arr)
print("Column Indices",np.argsort(arr,axis=0))#column
print("Row Indices",np.argsort(arr,axis=1))#row

[[108  45  70]
 [  9  36   6]
 [ 59 110   4]]
Column Indices [[1 1 2]
 [2 0 1]
 [0 2 0]]
Row Indices [[1 2 0]
 [2 0 1]
 [2 0 1]]


In [ ]:
12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.

In [6]:
a = np.random.randint(10,size=(3,3)) 
print("original matrix:\n",a) 
print("Transpose of a:\n",a.T) 
print("Multiplication:\n",a*a.T)

original matrix:
 [[0 9 9]
 [1 4 6]
 [6 9 1]]
Transpose of a:
 [[0 1 6]
 [9 4 9]
 [9 6 1]]
Multiplication:
 [[ 0  9 54]
 [ 9 16 54]
 [54 54  1]]


In [ ]:
13. Find solution for given linear equstion:
    #2x + 5y = 28 4x + 3*y = 81

In [9]:
a=np.array([[2,5],[4,3]])
b=np.array([28,81])
print("Solution of linear equations:",np.linalg.solve(a,b))

Solution of linear equations: [22.92857143 -3.57142857]


In [ ]:
14. Find Rank, Trace, Inverse, Determinant of a given matrix.
#     A=[[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [10]:
A=[[1,4,6],[9,2,8],[7,3,5]]
print("Rank:\n",np.linalg.matrix_rank(A))
print("Trace:\n",np.trace(A))
print("Determinant:\n",np.linalg.det(A))
print("Inverse:\n",np.linalg.inv(A))

Rank:
 3
Trace:
 8
Determinant:
 108.00000000000003
Inverse:
 [[-0.12962963 -0.01851852  0.18518519]
 [ 0.10185185 -0.34259259  0.42592593]
 [ 0.12037037  0.23148148 -0.31481481]]


In [ ]:
15. Find cube of a mtrix.

In [12]:
matrix=np.random.randint(1,99,(3,3))
np.linalg.matrix_power(matrix,3)

array([[ 635158, 1055810, 1190178],
       [ 634612, 1310449, 1294078],
       [ 758166, 1343833, 1335180]])