In [1]:
import numpy as np

In [ ]:
1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [9]:
x=0
array=np.random.randint(20,size=(3,3))
print(array)
np.count_nonzero(array)

[[16 11 15]
 [13  0 19]
 [ 4  0  5]]


7

In [ ]:
2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [16]:
array=np.random.randint(0,9,9)
print(array)
a=np.reshape(array,(3,3))
print(a)

[4 5 8 7 1 5 4 2 6]
[[4 5 8]
 [7 1 5]
 [4 2 6]]


In [ ]:
3. How to find the memory size of any array

In [24]:
array=np.random.randint(99,size=(5,5))
array.nbytes

100

In [ ]:
4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [23]:
array=np.ones((10,10))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [25]:
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
6. Normalize a 5x5 random matrix.

In [29]:
a=np.random.randint(99,size=(5,5))
print(((a-np.mean(a))/np.std(a)))

[[-1.56098452  1.26643569  0.14789583  1.42178845  1.3907179 ]
 [ 1.14215348 -0.62886797  1.26643569 -1.56098452  0.6139541 ]
 [-1.56098452 -0.87743238  0.80037741 -1.56098452 -0.84636183]
 [ 0.30324858  0.6139541   0.67609521 -0.53565631 -0.25602135]
 [-1.00171459 -0.53565631  1.08001238  0.33431914 -0.13173914]]


In [ ]:
7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [45]:
array=np.arange(0,11,)
print(array)
new = [np.where(np.logical_and(array>=3, array<=8))]
np.negative(new)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([[[-3, -4, -5, -6, -7, -8]]], dtype=int64)

In [ ]:
8. How to get the dates of yesterday, today and tomorrow?

In [37]:
from datetime import date
from datetime import timedelta
today=date.today()
yesterday=today-timedelta(days=1)
tomorrow=today+timedelta(days=1)
print(yesterday)
print(today)
print(tomorrow)

2020-02-13
2020-02-14
2020-02-15


In [ ]:
9. Generate two arrays of size 2X4 & 3X3, find difference between them.

In [ ]:
10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?

In [56]:
arr=np.array(['cat','dog','rat'])
# print(array)
# num=np.array.randint(array,size=(1,100))
# print(num)
np.arange(arr).reshape(1,100)

TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U3') dtype('<U3') dtype('<U3')

In [ ]:
11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [57]:
arr = np.linspace(0,1,12,endpoint=True)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
12. Given a two dimensional array, how to extract unique rows?

In [61]:
arr=np.random.randint(2,size=(5,5))
print(arr)
new_arr=np.unique(arr, axis=0)
print(new_arr)

[[1 0 0 0 0]
 [1 1 0 1 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [1 0 1 0 1]]
[[0 1 0 0 0]
 [0 1 1 1 0]
 [1 0 0 0 0]
 [1 0 1 0 1]
 [1 1 0 1 0]]


In [ ]:
13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [67]:
arry = np.zeros((3,3), [('x',float),('y',float)])
arry['x'], arry['y'] = np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
print(arry)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


In [ ]:
14. How to find the closest value (to a given scalar) in a vector?

In [66]:
value = 0.5
array = np.random.random(10)
array = np.asarray(array)
idx = (np.abs(array - value)).argmin()
ans = array[idx]
print(array,"\n",ans,"\n",value)

[0.76801692 0.92562852 0.14651353 0.78300149 0.8393021  0.68763644
 0.56309252 0.8292353  0.03593654 0.73135128] 
 0.5630925159077573 
 0.5


In [ ]:
15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [69]:
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.60787781 0.56871452 0.53177035 0.56622181 0.54786736
  0.47523579 0.53637365 0.46234385 0.50802135]
 [0.60787781 0.         0.45599523 0.8425649  0.13811031 0.09058967
  0.17852395 0.74670168 0.91693843 0.4177894 ]
 [0.56871452 0.45599523 0.         0.46333584 0.31823075 0.37060036
  0.30717769 0.34064955 0.61077301 0.06554127]
 [0.53177035 0.8425649  0.46333584 0.         0.72244952 0.75258446
  0.66433592 0.12935991 0.20276546 0.45873041]
 [0.56622181 0.13811031 0.31823075 0.72244952 0.         0.06246923
  0.09099287 0.61963058 0.81509582 0.28303647]
 [0.54786736 0.09058967 0.37060036 0.75258446 0.06246923 0.
  0.09027242 0.656112   0.83158356 0.32913249]
 [0.47523579 0.17852395 0.30717769 0.66433592 0.09099287 0.09027242
  0.         0.57118905 0.74138225 0.25688199]
 [0.53637365 0.74670168 0.34064955 0.12935991 0.61963058 0.656112
  0.57118905 0.         0.31698982 0.34445424]
 [0.46234385 0.91693843 0.61077301 0.20276546 0.81509582 0.83158356
  0.74138225 0.3169898

In [ ]:
16. How to sort an array by the nth column?

In [ ]:
17.How to tell if a given 2D array has null columns?

In [81]:
Z = np.random.randint(0,3,(3,10)).astype(float)
Z[:,0] = np.nan
G = np.isnan(Z)
print((G.all(axis=0)).any())

True


In [ ]:
18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [82]:
arry= np.random.randint(1,10,(5,5))
print(arry)
print(np.sum(arry[0:,3:]))

[[8 6 4 5 8]
 [7 6 2 8 2]
 [3 1 4 2 4]
 [9 3 1 8 8]
 [8 1 7 7 1]]
53


In [ ]:
19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [85]:
arr=np.random.randint(99,size=(5,5))
print(arr)
for i in range(5):
    arr[:,i]+=(i+1)
print(arr)

[[60 30 57  0 81]
 [15  3 62 33 69]
 [81 59 90 39 33]
 [33 38 93 48 42]
 [44 11 73 87 85]]
[[61 32 60  4 86]
 [16  5 65 37 74]
 [82 61 93 43 38]
 [34 40 96 52 47]
 [45 13 76 91 90]]


In [ ]:
20. Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [87]:
array=np.random.choice([True,False],size=100)
print(array)
print("No. of true are:",np.sum(array))

[ True False False  True  True  True  True False False False False  True
  True False  True False False  True False  True  True False  True False
  True False False False  True  True  True False False False  True False
 False False False False False  True False False False  True  True  True
 False False  True  True  True False  True False False False False  True
 False  True  True False  True False False False False  True  True  True
  True False False  True  True False False  True False  True False  True
  True False  True False False False False False False  True  True False
  True  True False False]
No. of true are: 44


In [ ]:
21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [ ]:
vec = np.array([1, 2, 3, 4, 5])
 
num_zero = 12 
#Create array with elements num_zero + len(vec)
new_arr = np.zeros(17)
new_arr[::4] = vec

print('New array is', new_arr, sep='\n')