In [1]:
import numpy as np

In [ ]:
1. Find dot product of two arrays.
a = [2j, 3j]
b = [2j, 3j]

In [3]:
a=np.array([2j,3j])
b=np.array([2j,3j])
a.dot(b)

(-13+0j)

In [ ]:
2. Create two arrays of 2-D and find dot product of it.

In [9]:
a=np.random.randint(100,size=(3,3))
b=np.random.randint(100,size=(3,3))
print(a)
print(a)
a.dot(b)

[[24 75 80]
 [83 49 53]
 [33 35  0]]
[[24 75 80]
 [83 49 53]
 [33 35  0]]


array([[12519,  7949,  7591],
       [14336,  6302,  6262],
       [ 6258,  2453,  2762]])

In [ ]:
3. Find vector product of given array.
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])

In [7]:
a=np.array([1+2j,3+4j])
b=np.array([5+6j,7+8j])

print(np.cross(a,b))
print(np.vdot(a,b))

-16j
(70-8j)


In [ ]:
4.First create given array without using direct value insted use numpy utlities and then find inner product for given array.
a = [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11]]
b = [[12 13 14 15] [16 17 18 19] [20 21 22 23]]

In [14]:
a=np.linspace(0,11,12)
b=np.linspace(12,23,12)
a=a.reshape(4,3)
b=b.reshape(4,3)
print(a)
print(b)
print(np.inner(a,b))

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
[[ 41.  50.  59.  68.]
 [158. 194. 230. 266.]
 [275. 338. 401. 464.]
 [392. 482. 572. 662.]]


In [ ]:
5. Using given two array try to print out 3rd given array.
a = np.array(['a', 'b', 'c'], dtype=object) b = np.array([1,2,3])
output = [['a', 'aa', 'aaa'], ['b', 'bb', 'bbb'], ['c', 'cc', 'ccc']]

In [17]:
a=np.array(['a','b','c'],dtype=object)
b=np.array([1,2,3])
c=np.multiply(a,b)
c=a.reshape(3,1)*b.reshape(1,3)
c

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

In [ ]:
6. Solve the system of equations 3 x0 + x1 = 9 and x0 + 2 x1 = 8

In [20]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

In [ ]:
7. Check the following solution is right or wrong uisng numpy utilities.
2x+3y=8 3x+y=5
solution: x=1 , y=2

In [21]:
a=np.array([[2,3],[3,1]])
b=np.array([8,5])
np.linalg.solve(a,b)

array([1., 2.])

In [ ]:
9. Write a program to add two arrays of different shape
a=[0.0,10.0,20.0,30.0]
b=[1.0,2.0,3.0]
output:
[[ 1., 2., 3.],

[ 11., 12., 13.],

[ 21., 22., 23.],

[ 31., 32., 33.]]

In [26]:
a=np.array([0.,10.,20.,30.])
b=np.array([1.,2.,3.,])
print(a,"\n",b)
a.reshape(4,1)+b.reshape(1,3)

[ 0. 10. 20. 30.] 
 [1. 2. 3.]


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
10. Create a 3 * 3 array find it's diagonal using numpy utilities.

In [30]:
n=np.random.randint(20,size=(3,3))
print(n)
np.diagonal(n)

[[ 0  5  0]
 [17 10  4]
 [ 9  7  4]]


array([ 0, 10,  4])

In [ ]:
11. Now find anti - diagonal in previous question using horizontal and vector flip.

In [35]:
print("n:",n)
print("1",np.fliplr(n).diagonal())
print("2",np.flipud(n).diagonal())

n: [[ 0  5  0]
 [17 10  4]
 [ 9  7  4]]
1 [ 0 10  9]
2 [ 9 10  0]


In [ ]:
12. Create given array without using indexing.
a = [[4, 0, 0], [0, 4, 0], [0, 0, 4], [0, 0, 0], [4, 0, 0], [0, 4, 0], [0, 0, 4]]

In [39]:
a=np.identity(3)*4
a

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [38]:
null=np.zeros(3)
null

array([0., 0., 0.])

In [40]:
np.vstack([a,null,a])

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.],
       [0., 0., 0.],
       [4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])