In [2]:
import numpy as np

In [ ]:
1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [30]:
print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\AnacondaPy\\lib\\site-packages\\numpy\\__config__.py'>


In [ ]:
2. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
Create a vector with values ranging from 10 to 49.

In [7]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
3. Create two arrays and stack them vertically

In [18]:
a=np.arange(1,5)
b=np.arange(1,5)
np.vstack([a,b])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
4. Reverse a vector (first element becomes last).

In [16]:
v=np.array([1,2,4])
v[::-1]

array([4, 2, 1])

In [ ]:
5. Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
np.random.randint(0,9,(3,3))

array([[5, 5, 6],
       [8, 7, 1],
       [5, 3, 3]])

In [ ]:
6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [34]:
num=[1,2,0,0,4,0]
np.nonzero(num)

(array([0, 1, 4], dtype=int64),)

In [ ]:
7. Create a 10x10 array with random values and find the minimum and maximum values

In [123]:
d=np.random.randint(1,1000,(10,10))
np.min(d)#Minimum

5

In [124]:
np.max(d)#Maximum

991

In [ ]:
8. Create a random vector of size 30 and find the mean value.

In [86]:
d=np.random.randint(1,100,(1,30))
d

array([[69, 96,  1, 38,  5, 69, 74, 81, 38, 83, 67,  4, 45,  6, 29, 63,
        23, 10, 76, 95,  4, 80, 21, 51, 18, 23, 37, 71, 27, 86]])

In [87]:
np.sum(d)/30

46.333333333333336

In [ ]:
9. Create a 2d array with 1 on the border and 0 inside

In [89]:
two_arr=np.ones((10,10))
two_arr[1:-1,1:-1]=0
print(two_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
10. How to add a border (filled with 0's) around an existing array

In [101]:
two_arr=np.zeros((10,10))
two_arr[1:-1,1:-1]=np.random.randint(1,10)
print(two_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 8. 8. 8. 8. 8. 8. 8. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
#[[ 0. 0. 0. 0. 0.] [ 1. 0. 0. 0. 0.] [ 0. 2. 0. 0. 0.] [ 0. 0. 3. 0. 0.] [ 0. 0. 0. 4. 0.]]

In [115]:
data=np.zeros((5,5))
data[1:2,:1]=1
data[2:3,1:2]=2
data[3:4,2:3]=3
data[4:5,3:4]=4
print(data)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
12. Create a 5*5 matrix with random values and normalize it.

In [126]:
data=np.random.randint(1,10,(5,5))
amax=np.max(data)
amin=np.min(data)
x=(data-amin)/(amax-amin)
print(x)

[[0.42857143 0.42857143 0.57142857 0.28571429 0.57142857]
 [0.42857143 0.71428571 0.14285714 0.14285714 0.28571429]
 [0.85714286 0.         1.         0.57142857 1.        ]
 [0.57142857 0.28571429 0.28571429 0.14285714 0.42857143]
 [1.         0.14285714 0.57142857 0.         0.        ]]


In [ ]:
13. How to find common values between two arrays

In [144]:
arr=np.random.randint(1,10,(3,3))
arr1=np.random.randint(1,10,(3,3))
print(np.intersect1d(arr,arr1))

[4 5 7 8]


In [ ]:
14. Consider a generator function that generates 10 integers and use it to build an array

In [148]:
def generator():
    for i in range(1,11):
        yield i
arr=np.fromiter(generator(),dtype=float)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
15. Subtract the mean of each row of a matrix

In [9]:
arr = np.random.randint(1,10,(10,5))
means = np.mean(arr, axis = 1)#rows
subs = arr.copy()
for i in range(arr.shape[0]):
    subs[i] = subs[i] - means[i]
print(subs)

[[-1 -2  3 -3  4]
 [ 2 -2 -2  0  3]
 [ 2  2  1  0 -4]
 [ 2  1  0 -2 -3]
 [ 3 -2  0  2 -2]
 [ 2 -2 -1  2 -1]
 [ 0 -2 -2  2  0]
 [-1  4 -2 -1  0]
 [ 0  0  3 -3 -1]
 [ 2  1 -1  2 -4]]


In [ ]:
16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [6]:
a =np.random.randint(0,10,(1,3))
b=np.random.randint(0,10,(3,1))
sums = []
for i in np.nditer(a):
    for j in np.nditer(b):
        sums.append(i+j)
print(np.array(sums).reshape(3,3))

[12, 14, 16, 10, 12, 14, 10, 12, 14]
[[12 14 16]
 [10 12 14]
 [10 12 14]]


In [ ]:
17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [5]:
v = np.linspace(5, 50, 10)#it will take only 10 values
v

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])